"""
===============================================================================
BASELINE SCRIPT 
===============================================================================
This notebook runs baseline experiments (MLP, LASSO, RF) on the datasets generated by the split.py and DEG.py scripts. It evaluates the performance of these models on the specified problem.
Modify the following variables in the "Global configuration" section:

  * PROBLEM_NAME   : Folder name of the specific problem/dataset being evaluated.
                     (e.g., "colon_sigmoid_vs_colon_transverse", "ppmi").
  * PROJ_PATH      : Absolute path to the root of the GeneRAIN repository.
  * LABEL_COL      : The target column name to predict in your CSVs.
                     (Note: this must be "diagnosis" if PROBLEM_NAME is "ppmi", 
                     or "tissue" if evaluating tissue datasets).
  * SPLITS_DIR     : Path to the directory containing train/val/test CSV splits.
  * GENES_DIR      : Path to the directory containing gene lists (HVG1000 and DEG).
  * RESULTS_DIR    : Path to the directory where baseline results will be saved.
  * PROCESS_DEG    : Set to True if you want to process the DEG dataset as well.
  * PROCESS_SYNTHETIC : Set to True if you want to process the synthetic dataset as well.
  * CHECKPOINT     : Path to the downloaded GeneRAIN model weights (.pth).
  * PARAM_JSON     : Path to the GeneRAIN model configuration file (.json).
  * CUDA_VISIBLE_DEVICES : GPU ID allocated for training (e.g., "0" or "1").
"""
  

import os
import sys
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.metrics import f1_score, recall_score, confusion_matrix
from IPython.display import display
from sklearn.preprocessing import StandardScaler
import umap

# ==========================================
# 1. Global configuration and paths
# ==========================================
def find_repo_root(start: Path | None = None) -> Path:
    here = (start or Path.cwd()).resolve()
    for candidate in [here, *here.parents]:
        if (candidate / "config.json").exists() and (candidate / "src").is_dir():
            return candidate
    raise FileNotFoundError("Could not find repo root (expected config.json + src/)")

PROJ_PATH    = find_repo_root() 
PROBLEM_NAME = "ppmi"
SPLITS_DIR   = f"{PROJ_PATH}/data/processed/{PROBLEM_NAME}/splits"  
GENES_DIR    = f"{PROJ_PATH}/data/processed/{PROBLEM_NAME}/genes"
RESULTS_DIR  = f"{PROJ_PATH}/results/{PROBLEM_NAME}/baseline"

PARAM_JSON  = f"{PROJ_PATH}/jsons/exp3_BERT_Pred_Genes_Binning_By_Gene.param_config.json"
CHECKPOINT  = f"{PROJ_PATH}/data/models/GeneRAIN.BERT_Pred_Genes_Binning_By_Gene.pth"
LABEL_COL   = "diagnosis" if PROBLEM_NAME == "ppmi" else "tissue"
PROCESS_DEG = True 
PROCESS_SYNTHETIC = True

os.environ['PARAM_JSON_FILE'] = PARAM_JSON
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

sys.path.append(f"{PROJ_PATH}/src")
sys.path.append(str(PROJ_PATH))

from utils.config_loader import Config
import anal_utils as au
from utils.utils import get_device
from utils.checkpoint_utils import load_checkpoint
from train.common import initiate_model

# Out files
Path(RESULTS_DIR).mkdir(parents=True, exist_ok=True)
OPTUNA_TRIALS_CSV = Path(RESULTS_DIR) / f"optuna_mlp_trials.csv"
OPTUNA_TRIALS_CSV.unlink(missing_ok=True)
RESULTS_CSV = Path(RESULTS_DIR) / "best_config_baseline.csv"

pd.set_option("display.max_colwidth", None)
config = Config()

# ==========================================
# 2. Auxiliary functions
# ==========================================
def append_optuna_trials_block(df_trials, section_title, dataset_name, train_setup):
    df_to_write = df_trials.copy()
    df_to_write.insert(0, "section", section_title)
    df_to_write.insert(1, "dataset", dataset_name)
    df_to_write.insert(2, "train_setup", train_setup)

    write_header = not OPTUNA_TRIALS_CSV.exists()
    with OPTUNA_TRIALS_CSV.open("a", encoding="utf-8") as handle:
        df_to_write.to_csv(handle, index=False, header=write_header)
    return OPTUNA_TRIALS_CSV

def summarize_test_metrics(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    tn, fp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()[:2]
    return {
        "test_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        "test_sensitivity": float(recall_score(y_true, y_pred, average="macro", zero_division=0)),
        "test_specificity": float(tn / (tn + fp)) if (tn + fp) > 0 else 0.0,
    }


def _scale_stats(X):
    X = np.asarray(X, dtype=np.float64)
    flat = X.ravel()
    return {
        "n_samples": int(X.shape[0]),
        "n_features": int(X.shape[1]),
        "mean": float(np.mean(flat)),
        "var": float(np.var(flat)),
        "std": float(np.std(flat)),
        "min": float(np.min(flat)),
        "p01": float(np.percentile(flat, 1)),
        "p05": float(np.percentile(flat, 5)),
        "p50": float(np.percentile(flat, 50)),
        "p95": float(np.percentile(flat, 95)),
        "p99": float(np.percentile(flat, 99)),
        "max": float(np.max(flat)),
    }

# ==========================================
# 3. Loading data: splits and gene lists
# ==========================================
print("--- Loading data splits ---")
df_train_real = au.load_real_split(Path(SPLITS_DIR) / "train.csv", "RealTrain", LABEL_COL)
df_val_real   = au.load_real_split(Path(SPLITS_DIR) / "val.csv", "RealVal", LABEL_COL)
df_test_real  = au.load_real_split(Path(SPLITS_DIR) / "test.csv", "RealTest", LABEL_COL)

df_merged_all = pd.concat([df_train_real, df_val_real, df_test_real], axis=0)

# =======================
# A) Processing HVG1000
# =======================
hvg_file = Path(GENES_DIR) / "top1000_hvg.txt"
if not hvg_file.exists():
    raise FileNotFoundError("HVG file not found. Please run split.py first!")

with open(hvg_file, "r") as f:
    hvg_1000_genes = [line.strip() for line in f if line.strip()]

# Cut real data to HVG
df_hvg_1000 = df_merged_all[[LABEL_COL, *hvg_1000_genes]].copy()

# Append synthetic data for HVG if requested
if PROCESS_SYNTHETIC:
    syn_hvg_path = PROJ_PATH / "data" / "processed" / PROBLEM_NAME / "synthetic" / "combined" / "synthetic_combined.csv"
    
    if syn_hvg_path.exists():
        print("Appending TVAE synthetic data for HVG...")
        df_syn_hvg = pd.read_csv(syn_hvg_path, index_col=0)
        df_syn_hvg.index = [f"Synthetic_{i}" for i in range(len(df_syn_hvg))]
        df_hvg_1000 = pd.concat([df_hvg_1000, df_syn_hvg], axis=0)
    else:
        print(f"[WARNING] Synthetic HVG requested but not found at {syn_hvg_path}")

mat_hvg_1000 = df_hvg_1000[hvg_1000_genes].values.astype(np.float32)
bool_mask_hvg = np.ones(len(df_hvg_1000), dtype=bool)

# =======================
# B) Processing DEG
# =======================
if PROCESS_DEG:
    deg_file = Path(GENES_DIR) / "degs_filtered.txt"
    if not deg_file.exists():
        raise FileNotFoundError("DEG file not found. Please run DEG.py first!")
        
    with open(deg_file, "r") as f:
        deg_genes = [line.strip() for line in f if line.strip()]

    # Cut real data to DEG
    df_deg = df_merged_all[[LABEL_COL, *deg_genes]].copy()

    # Append synthetic data for DEG if requested
    if PROCESS_SYNTHETIC:
        # Ruta ajustada a la subcarpeta 'combined_deg'
        syn_deg_path = PROJ_PATH / "data" / "processed" / PROBLEM_NAME / "synthetic" / "combined_deg" / "combined_synthetic.csv"
        
        if syn_deg_path.exists():
            print("Appending TVAE synthetic data for DEG...")
            df_syn_deg = pd.read_csv(syn_deg_path, index_col=0)
            df_syn_deg.index = [f"Synthetic_{i}" for i in range(len(df_syn_deg))]
            df_deg = pd.concat([df_deg, df_syn_deg], axis=0)
        else:
            print(f"[WARNING] Synthetic DEG requested but not found at {syn_deg_path}")

    mat_deg = df_deg[deg_genes].values.astype(np.float32)
    bool_mask_deg = np.ones(len(df_deg), dtype=bool)

# ==========================================
# 4. Load model and prepare datasets
# ==========================================
device = get_device()
model = initiate_model()
model, optimizer, scheduler = load_checkpoint(model, None, CHECKPOINT, None)
model = model.to(device).eval()

datasets_raw = {}
datasets_raw["HVG1000"] = au.splits(df_hvg_1000, bool_mask_hvg, mat_hvg_1000, label_col=LABEL_COL)
if PROCESS_DEG:
    datasets_raw["DEG"]     = au.splits(df_deg, bool_mask_deg, mat_deg, label_col=LABEL_COL)

# ==========================================
# 5. Run baseline experiments: MLP, LASSO, RF
# ==========================================
results_rows = []
mlp_plot_payload = []

# 1. Define models and training setups
model_list = ["MLP", "LASSO", "RF"]
train_setups = ["Real"]

if PROCESS_SYNTHETIC:
    train_setups.append("Real+Synthetic")

# 2. Dynamic construction of the Experiment Grid
experiment_grid = []

# A) Always add HVG1000 combinations
for mod in model_list:
    for setup in train_setups:
        experiment_grid.append(("HVG1000", mod, setup))
        
# B) Add DEG combinations only if requested
if PROCESS_DEG:
    for mod in model_list:
        for setup in train_setups:
            experiment_grid.append(("DEG", mod, setup))

print(f"\n[INFO] Experiment grid configured with {len(experiment_grid)} combinations:")
for exp in experiment_grid:
    print(f"  -> {exp}")

rows = []
for ds_name in sorted(datasets_raw.keys()):
    ds_raw = datasets_raw[ds_name]
    for setup in train_setups:
        # Check the correct internal key depending on the setup
        key = "X_train_real" if setup == "Real" else "X_train_comb"
        if key in ds_raw:
            rows.append({
                "space": "raw", 
                "dataset": ds_name, 
                "train_setup": setup, 
                **_scale_stats(ds_raw[key])
            })

df_scale_diagnostics = pd.DataFrame(rows).sort_values(["space", "dataset", "train_setup"]).reset_index(drop=True)
print("\nScale diagnostics (before scaling):")
display(df_scale_diagnostics)


for ds_name, model_name, train_setup in experiment_grid:
    ds = datasets_raw[ds_name]
    au.set_seed(42)

    X_train_real_raw = ds["X_train_real"]
    y_train_real_enc = ds["y_train_real_enc"]
    X_val_raw = ds["X_val"]
    y_val_enc = ds["y_val_enc"]
    X_test_raw = ds["X_test"]
    y_test_enc = ds["y_test_enc"]

    pd_label = ds["pd_label"]
    control_label = ds["control_label"]
    le = ds["le"]

    idx_train_real_bal = au.balanced_real_indices(
        y_train_real_enc, pd_label, control_label, seed=42,
    )

    X_train = X_train_real_raw[idx_train_real_bal]
    y_train = y_train_real_enc[idx_train_real_bal]

    # Scale data for baseline
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val_raw_scaled = scaler.transform(X_val_raw)
    X_test_raw_scaled = scaler.transform(X_test_raw)

    best_params = None
    preds = None
    
    if model_name == "MLP":
        raw_mlp_param_grid = {
            "dropout": [0.3, 0.4, 0.5],
            "batch_size": [32],
            "max_epochs": [10],
            "patience": [10],
            "min_delta": [0.005],
            "schedule_ratio": [0.9],
        }

        train_ba, val_ba, test_ba, preds, best_params, mlp_details = au.run_mlp_optuna_grid(
            X_train=X_train,
            y_train=y_train,
            X_test=X_test_raw_scaled,
            y_test=y_test_enc,
            n_classes=len(le.classes_),
            device=device,
            seed=42,
            X_val=X_val_raw_scaled,
            y_val=y_val_enc,
            optimize_metric="val_balanced_accuracy",
            return_details=True,
            lr_grid=[5e-4, 1e-4],
            param_grid=raw_mlp_param_grid,
            final_save_all_epochs=True,
            final_checkpoint_dir=Path(RESULTS_DIR) / "raw_mlp_epoch_checkpoints" / f"{ds_name}_{train_setup}",
            final_checkpoint_prefix=f"{ds_name}_{train_setup}",
            final_early_stopping=False,
        )
        
        mlp_plot_payload.append({
            "dataset": ds_name,
            "train_setup": train_setup,
            "best_params": best_params,
            "final_history": mlp_details["final_history"],
            "final_diagnostics": mlp_details.get("final_diagnostics"),
        })
        trials_display = au.prepare_optuna_trials_display(mlp_details["trials_table"], mlp_details)
        print(f"\nMLP baseline - {ds_name} - {train_setup}")
        display(trials_display.head(1))
        append_optuna_trials_block(trials_display, "baseline", ds_name, train_setup)

    elif model_name == "LASSO":
        train_ba, val_ba, test_ba, preds, best_params = au.run_lasso(
            X_train=X_train, y_train=y_train, X_test=X_test_raw_scaled, y_test=y_test_enc, seed=42
        )

    elif model_name == "RF":
        train_ba, val_ba, test_ba, preds, best_params = au.run_rf(
            X_train=X_train, y_train=y_train, X_test=X_test_raw_scaled, y_test=y_test_enc, seed=42
        )

    test_metrics = summarize_test_metrics(y_test_enc, preds)

    results_rows.append({
        "model": model_name,
        "dataset": ds_name,
        "train_setup": train_setup,
        "train_ba": float(train_ba),
        "val_ba": float(val_ba),
        "test_ba": float(test_ba),
        "test_f1": test_metrics["test_f1"],
        "test_sensitivity": test_metrics["test_sensitivity"],
        "test_specificity": test_metrics["test_specificity"],
        "best_params": str(best_params) if best_params is not None else None,
    })

# ==========================================
# 6. Save results
# ==========================================
df_results = pd.DataFrame(results_rows).sort_values(["dataset", "model", "train_setup"]).reset_index(drop=True)

print("\nExperiment results - BASELINES:")
print(f"Total experiments run: {len(df_results)}")
display(df_results)

df_results.to_csv(RESULTS_CSV, index=False)
print(f"Results saved in {RESULTS_CSV}")
    
# ==========================================
# 7. Run plotting functions
# ==========================================

print("\n--- Generating plots ---")

# 1. Dynamically determine the datasets to plot
dataset_order = ["HVG1000"]
if PROCESS_DEG:
    dataset_order.append("DEG")

# 2. Build the plotting grid based on the active datasets and train setups
plot_grid = []
for ds_name in dataset_order:
    for setup in train_setups:
        plot_grid.append((ds_name, setup))

# 3. Generate the MLP diagnostics grid
au.plot_best_mlp_diagnostics_grid(
    mlp_plot_payload,
    "Best-config metrics - BASELINES",
    plot_grid,
    results_dir=RESULTS_DIR,
)

# 4. Generate the Model Balanced Accuracy barplots
au.plot_model_ba_barplots(
    df_results=None,
    section_title="Best-config BA summary - BASELINES",
    dataset_order=dataset_order,
    model_order=["MLP", "LASSO", "RF"],
    load_saved=True,
    results_dir=RESULTS_DIR,
    csv="best_config_baseline.csv"
)

# 5. Generate UMAPs dynamically for the evaluated datasets
for ds_name in dataset_order:
    ds = datasets_raw[ds_name]
    au.plot_umap_by_class(ds["X_test"], ds["y_test_enc"], ds["le"], ds_name, RESULTS_DIR)

print(f"[OK] All plots saved successfully in {RESULTS_DIR}")